sudo: required

language: go

services:
  - docker
branches:
  only:
    - master  

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/go-base:1.0 .
      - docker images
      - docker tag jonathan99/go-base:1.0 $DOCKER_USERNAME/go-base:1.0
      - docker push $DOCKER_USERNAME/go-base:1.0

    - stage: test
      script:
      - docker run -it -p 8080:8000 --net=host --name api-go jonathan99/go-base:1.0
      - docker ps -a
